extern malloc

;########### SECCION DE DATOS
section .data

;########### SECCION DE TEXTO (PROGRAMA)
section .text

; Completar las definiciones (serán revisadas por ABI enforcer):
TUIT_MENSAJE_OFFSET EQU 0
TUIT_FAVORITOS_OFFSET EQU 0
TUIT_RETUITS_OFFSET EQU 0
TUIT_ID_AUTOR_OFFSET EQU 0
TUIT_SIZE EQU 0

PUBLICACION_NEXT_OFFSET EQU 0
PUBLICACION_VALUE_OFFSET EQU 0
PUBLICACION_SIZE EQU 0

FEED_FIRST_OFFSET EQU 0 
FEED_SIZE EQU 0

USUARIO_FEED_OFFSET EQU 0;
USUARIO_SEGUIDORES_OFFSET EQU 0; 
USUARIO_CANT_SEGUIDORES_OFFSET EQU 0; 
USUARIO_SEGUIDOS_OFFSET EQU 0; 
USUARIO_CANT_SEGUIDOS_OFFSET EQU 0; 
USUARIO_BLOQUEADOS_OFFSET EQU 0; 
USUARIO_CANT_BLOQUEADOS_OFFSET EQU 0; 
USUARIO_ID_OFFSET EQU 0; 
USUARIO_SIZE EQU 0

; tuit_t **trendingTopic(usuario_t *usuario, uint8_t (*esTuitSobresaliente)(tuit_t *));
global trendingTopic 
trendingTopic:
    ret
